---
title: Thông báo lỗi Dịch vụ Siêu dữ liệu được Quản lý
ms.author: pebaum
author: pebaum
ms.date: 04/21/2020
ms.audience: ITPro
ms.topic: article
ms.service: o365-administration
ROBOTS: NOINDEX, NOFOLLOW
localization_priority: Normal
ms.custom:
- "1246"
- "5200021"
ms.assetid: 15091086-2ac9-4e99-94be-a08a17386e6e
ms.openlocfilehash: 58394b854877aaf2f537c33195193d23cc3891524cb2f867246ba4bf5f9e73a0
ms.sourcegitcommit: b5f7da89a650d2915dc652449623c78be6247175
ms.translationtype: MT
ms.contentlocale: vi-VN
ms.lasthandoff: 08/05/2021
ms.locfileid: "54099020"
---
# <a name="managed-metadata-service-error-message"></a>Thông báo lỗi Dịch vụ Siêu dữ liệu được Quản lý

Khi bạn mở Kho Thuật ngữ, bạn có thể thấy thông báo lỗi: "Dịch vụ siêu dữ liệu được quản lý hoặc Kết nối hiện không sẵn dùng. Dịch vụ Web Siêu dữ liệu được Quản lý hoặc Nhóm Ứng dụng có thể chưa được bắt đầu. Vui lòng liên hệ với Người quản trị của bạn."
  
Nếu hơn 24 giờ trôi qua kể từ khi bạn gặp sự cố này lần đầu, vui lòng ghi nhật ký trường hợp hỗ trợ. Chúng tôi hiểu rằng 24 giờ có thể trông giống như một khoảng thời gian dài. Trong nhiều trường hợp, chúng tôi đang tìm giải pháp để vui lòng cung cấp cho chúng tôi ít nhất 24 giờ.
  